import { Question, QuestionType } from "@/types";

export interface SubjectQuestions {
  [subject: string]: {
    [examType: string]: Question[];
  };
}

export const DIAGNOSTIC_QUESTIONS: SubjectQuestions = {
  Mathematics: {
    default: [
      {
        id: "math-q1",
        topicId: "math-algebra",
        question: "Solve for x: $2x + 5 = 13$",
        type: QuestionType.MCQ,
        options: ["x = 4", "x = 9", "x = 3", "x = 6"],
        correctAnswer: "x = 4",
        difficulty: 0.2,
        hints: ["Subtract 5 from both sides first"],
        explanation: "$2x + 5 = 13 \\Rightarrow 2x = 8 \\Rightarrow x = 4$",
      },
      {
        id: "math-q2",
        topicId: "math-functions",
        question: "If $f(x) = x^2 - 3x + 2$, find $f(3)$",
        type: QuestionType.MCQ,
        options: ["2", "0", "5", "8"],
        correctAnswer: "2",
        difficulty: 0.3,
        hints: ["Substitute x = 3 into the function"],
        explanation: "$f(3) = 9 - 9 + 2 = 2$",
      },
      {
        id: "math-q3",
        topicId: "math-trigonometry",
        question: "What is $\\sin(30°)$?",
        type: QuestionType.MCQ,
        options: ["$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$1$", "$\\frac{\\sqrt{2}}{2}$"],
        correctAnswer: "$\\frac{1}{2}$",
        difficulty: 0.3,
        hints: ["Think of the 30-60-90 triangle"],
        explanation: "In a 30-60-90 triangle, $\\sin(30°) = \\frac{1}{2}$",
      },
      {
        id: "math-q4",
        topicId: "math-calculus-diff",
        question: "Find $\\frac{d}{dx}(x^3)$",
        type: QuestionType.MCQ,
        options: ["$3x^2$", "$x^2$", "$3x^3$", "$x^4$"],
        correctAnswer: "$3x^2$",
        difficulty: 0.4,
        hints: ["Use the power rule: $\\frac{d}{dx}(x^n) = nx^{n-1}$"],
        explanation: "Power rule: $\\frac{d}{dx}(x^3) = 3x^{3-1} = 3x^2$",
      },
      {
        id: "math-q5",
        topicId: "math-calculus-int",
        question: "Evaluate $\\int x^2 dx$",
        type: QuestionType.MCQ,
        options: ["$\\frac{x^3}{3} + C$", "$2x + C$", "$x^3 + C$", "$\\frac{x^2}{2} + C$"],
        correctAnswer: "$\\frac{x^3}{3} + C$",
        difficulty: 0.4,
        hints: ["Reverse the power rule"],
        explanation: "$\\int x^n dx = \\frac{x^{n+1}}{n+1} + C$, so $\\int x^2 dx = \\frac{x^3}{3} + C$",
      },
    ],
    "IIT JEE": [
      {
        id: "jee-math-q1",
        topicId: "jee-algebra",
        question: "If $\\omega$ is a complex cube root of unity, then $1 + \\omega + \\omega^2 = $",
        type: QuestionType.MCQ,
        options: ["0", "1", "-1", "3"],
        correctAnswer: "0",
        difficulty: 0.5,
        hints: ["Use the property of cube roots of unity"],
        explanation: "For cube roots of unity: $1 + \\omega + \\omega^2 = 0$",
      },
      {
        id: "jee-math-q2",
        topicId: "jee-matrices",
        question: "If $A = \\begin{bmatrix} 1 & 2 \\\\ 3 & 4 \\end{bmatrix}$, find $|A|$",
        type: QuestionType.MCQ,
        options: ["-2", "2", "-10", "10"],
        correctAnswer: "-2",
        difficulty: 0.4,
        hints: ["Determinant of 2×2 matrix: ad - bc"],
        explanation: "$|A| = (1)(4) - (2)(3) = 4 - 6 = -2$",
      },
      {
        id: "jee-math-q3",
        topicId: "jee-calculus",
        question: "Evaluate: $\\lim_{x \\to 0} \\frac{\\sin x}{x}$",
        type: QuestionType.MCQ,
        options: ["1", "0", "$\\infty$", "Does not exist"],
        correctAnswer: "1",
        difficulty: 0.5,
        hints: ["This is a standard limit"],
        explanation: "$\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$ (standard result)",
      },
      {
        id: "jee-math-q4",
        topicId: "jee-coordinate",
        question: "The distance between points $(1, 2)$ and $(4, 6)$ is:",
        type: QuestionType.MCQ,
        options: ["5", "7", "25", "3"],
        correctAnswer: "5",
        difficulty: 0.3,
        hints: ["Use distance formula: $\\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$"],
        explanation: "$d = \\sqrt{(4-1)^2 + (6-2)^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5$",
      },
      {
        id: "jee-math-q5",
        topicId: "jee-vectors",
        question: "If $\\vec{a} = 2\\hat{i} + 3\\hat{j}$, find $|\\vec{a}|$",
        type: QuestionType.MCQ,
        options: ["$\\sqrt{13}$", "5", "$\\sqrt{5}$", "13"],
        correctAnswer: "$\\sqrt{13}$",
        difficulty: 0.4,
        hints: ["Magnitude = $\\sqrt{a_x^2 + a_y^2}$"],
        explanation: "$|\\vec{a}| = \\sqrt{2^2 + 3^2} = \\sqrt{4 + 9} = \\sqrt{13}$",
      },
      {
        id: "jee-math-q6",
        topicId: "jee-probability",
        question: "In how many ways can 5 books be arranged on a shelf?",
        type: QuestionType.MCQ,
        options: ["120", "60", "24", "5"],
        correctAnswer: "120",
        difficulty: 0.3,
        hints: ["This is a permutation: n!"],
        explanation: "$5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120$",
      },
    ],
    "AP Calculus": [
      {
        id: "ap-q1",
        topicId: "ap-limits",
        question: "Evaluate: $\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}$",
        type: QuestionType.MCQ,
        options: ["4", "0", "2", "Does not exist"],
        correctAnswer: "4",
        difficulty: 0.4,
        hints: ["Factor the numerator as difference of squares"],
        explanation: "$\\frac{x^2-4}{x-2} = \\frac{(x-2)(x+2)}{x-2} = x+2$. At $x=2$: $2+2=4$",
      },
      {
        id: "ap-q2",
        topicId: "ap-derivatives",
        question: "Find $f'(x)$ if $f(x) = 3x^4 - 2x^2 + 5$",
        type: QuestionType.MCQ,
        options: ["$12x^3 - 4x$", "$12x^3 - 2x$", "$3x^3 - 2x$", "$12x^4 - 4x^2$"],
        correctAnswer: "$12x^3 - 4x$",
        difficulty: 0.4,
        hints: ["Apply power rule to each term"],
        explanation: "$f'(x) = 12x^3 - 4x + 0 = 12x^3 - 4x$",
      },
      {
        id: "ap-q3",
        topicId: "ap-applications-diff",
        question: "A balloon's radius increases at $2$ cm/s. How fast does the volume change when $r = 3$ cm? (V = $\\frac{4}{3}\\pi r^3$)",
        type: QuestionType.MCQ,
        options: ["$72\\pi$ cm³/s", "$36\\pi$ cm³/s", "$24\\pi$ cm³/s", "$108\\pi$ cm³/s"],
        correctAnswer: "$72\\pi$ cm³/s",
        difficulty: 0.6,
        hints: ["Use $\\frac{dV}{dt} = 4\\pi r^2 \\frac{dr}{dt}$"],
        explanation: "$\\frac{dV}{dt} = 4\\pi (3)^2 (2) = 72\\pi$ cm³/s",
      },
      {
        id: "ap-q4",
        topicId: "ap-integrals",
        question: "Evaluate: $\\int_0^2 3x^2 dx$",
        type: QuestionType.MCQ,
        options: ["8", "6", "12", "4"],
        correctAnswer: "8",
        difficulty: 0.5,
        hints: ["Integrate, then apply bounds"],
        explanation: "$[x^3]_0^2 = 2^3 - 0^3 = 8$",
      },
      {
        id: "ap-q5",
        topicId: "ap-applications-int",
        question: "Find the area under $y = x^2$ from $x = 0$ to $x = 2$",
        type: QuestionType.MCQ,
        options: ["$\\frac{8}{3}$", "4", "$\\frac{4}{3}$", "2"],
        correctAnswer: "$\\frac{8}{3}$",
        difficulty: 0.5,
        hints: ["Area = $\\int_0^2 x^2 dx$"],
        explanation: "$\\int_0^2 x^2 dx = [\\frac{x^3}{3}]_0^2 = \\frac{8}{3}$",
      },
    ],
    "GCSE": [
      {
        id: "gcse-q1",
        topicId: "gcse-number",
        question: "What is 25% of 80?",
        type: QuestionType.MCQ,
        options: ["20", "25", "15", "40"],
        correctAnswer: "20",
        difficulty: 0.2,
        hints: ["25% = 1/4"],
        explanation: "25% of 80 = 0.25 × 80 = 20",
      },
      {
        id: "gcse-q2",
        topicId: "gcse-algebra",
        question: "Simplify: $3x + 5x - 2x$",
        type: QuestionType.MCQ,
        options: ["$6x$", "$8x$", "$10x$", "$4x$"],
        correctAnswer: "$6x$",
        difficulty: 0.2,
        hints: ["Combine like terms"],
        explanation: "$3x + 5x - 2x = (3 + 5 - 2)x = 6x$",
      },
      {
        id: "gcse-q3",
        topicId: "gcse-geometry",
        question: "What is the area of a rectangle with length 8cm and width 5cm?",
        type: QuestionType.MCQ,
        options: ["40 cm²", "26 cm²", "13 cm²", "80 cm²"],
        correctAnswer: "40 cm²",
        difficulty: 0.2,
        hints: ["Area = length × width"],
        explanation: "Area = 8 × 5 = 40 cm²",
      },
      {
        id: "gcse-q4",
        topicId: "gcse-probability",
        question: "A fair die is rolled. What is the probability of getting an even number?",
        type: QuestionType.MCQ,
        options: ["$\\frac{1}{2}$", "$\\frac{1}{3}$", "$\\frac{1}{6}$", "$\\frac{2}{3}$"],
        correctAnswer: "$\\frac{1}{2}$",
        difficulty: 0.3,
        hints: ["Even numbers on a die: 2, 4, 6"],
        explanation: "3 even numbers out of 6 total = $\\frac{3}{6} = \\frac{1}{2}$",
      },
      {
        id: "gcse-q5",
        topicId: "gcse-statistics",
        question: "Find the mean of: 4, 6, 8, 10, 12",
        type: QuestionType.MCQ,
        options: ["8", "6", "10", "7"],
        correctAnswer: "8",
        difficulty: 0.2,
        hints: ["Mean = sum ÷ count"],
        explanation: "Mean = (4+6+8+10+12) ÷ 5 = 40 ÷ 5 = 8",
      },
    ],
  },
  Physics: {
    default: [
      {
        id: "phys-q1",
        topicId: "phys-mechanics",
        question: "A car travels 100m in 5s. What is its average speed?",
        type: QuestionType.MCQ,
        options: ["20 m/s", "500 m/s", "0.05 m/s", "95 m/s"],
        correctAnswer: "20 m/s",
        difficulty: 0.2,
        hints: ["Speed = distance ÷ time"],
        explanation: "Speed = 100m ÷ 5s = 20 m/s",
      },
      {
        id: "phys-q2",
        topicId: "phys-mechanics",
        question: "What is the acceleration due to gravity on Earth (approximate)?",
        type: QuestionType.MCQ,
        options: ["10 m/s²", "9.8 m/s²", "100 m/s²", "1 m/s²"],
        correctAnswer: "9.8 m/s²",
        difficulty: 0.2,
        hints: ["Standard value on Earth's surface"],
        explanation: "g ≈ 9.8 m/s² (often rounded to 10 m/s² for calculations)",
      },
      {
        id: "phys-q3",
        topicId: "phys-electricity",
        question: "If V = 12V and R = 4Ω, find the current I using Ohm's Law",
        type: QuestionType.MCQ,
        options: ["3 A", "48 A", "0.33 A", "8 A"],
        correctAnswer: "3 A",
        difficulty: 0.3,
        hints: ["Ohm's Law: V = IR, so I = V/R"],
        explanation: "I = V/R = 12/4 = 3 A",
      },
      {
        id: "phys-q4",
        topicId: "phys-waves",
        question: "A wave has frequency 50 Hz and wavelength 2m. What is its speed?",
        type: QuestionType.MCQ,
        options: ["100 m/s", "25 m/s", "52 m/s", "48 m/s"],
        correctAnswer: "100 m/s",
        difficulty: 0.3,
        hints: ["v = f × λ"],
        explanation: "v = 50 × 2 = 100 m/s",
      },
      {
        id: "phys-q5",
        topicId: "phys-thermo",
        question: "What happens to the temperature of water as it boils?",
        type: QuestionType.MCQ,
        options: ["Stays constant at 100°C", "Keeps increasing", "Decreases", "Fluctuates"],
        correctAnswer: "Stays constant at 100°C",
        difficulty: 0.2,
        hints: ["During phase change, temperature remains constant"],
        explanation: "At boiling point, heat energy is used for phase change, not temperature increase",
      },
    ],
    "IIT JEE": [
      {
        id: "jee-phys-q1",
        topicId: "jee-mechanics",
        question: "A ball is thrown upward with velocity 20 m/s. Maximum height reached is (g = 10 m/s²):",
        type: QuestionType.MCQ,
        options: ["20 m", "40 m", "10 m", "200 m"],
        correctAnswer: "20 m",
        difficulty: 0.4,
        hints: ["Use $v^2 = u^2 - 2gh$, where v = 0 at max height"],
        explanation: "$0 = 400 - 20h \\Rightarrow h = 20$ m",
      },
      {
        id: "jee-phys-q2",
        topicId: "jee-electro",
        question: "Two charges +q and -q are separated by distance d. The electric field at midpoint is:",
        type: QuestionType.MCQ,
        options: ["$\\frac{4kq}{d^2}$ towards -q", "Zero", "$\\frac{2kq}{d^2}$", "$\\frac{kq}{d^2}$"],
        correctAnswer: "$\\frac{4kq}{d^2}$ towards -q",
        difficulty: 0.6,
        hints: ["Both fields point in the same direction (towards -q)"],
        explanation: "E = 2 × k × q / (d/2)² = 8kq/d². Correction: Each field is $\\frac{4kq}{d^2}$, pointing same direction.",
      },
      {
        id: "jee-phys-q3",
        topicId: "jee-shm",
        question: "In SHM, acceleration is maximum when displacement is:",
        type: QuestionType.MCQ,
        options: ["Maximum", "Zero", "Half of maximum", "Increasing"],
        correctAnswer: "Maximum",
        difficulty: 0.4,
        hints: ["a = -ω²x"],
        explanation: "Since a = -ω²x, acceleration is maximum when |x| is maximum",
      },
      {
        id: "jee-phys-q4",
        topicId: "jee-optics",
        question: "A lens has focal length -20 cm. It is a:",
        type: QuestionType.MCQ,
        options: ["Concave lens", "Convex lens", "Plano-convex", "Depends on medium"],
        correctAnswer: "Concave lens",
        difficulty: 0.3,
        hints: ["Negative focal length indicates diverging lens"],
        explanation: "Concave (diverging) lenses have negative focal length",
      },
      {
        id: "jee-phys-q5",
        topicId: "jee-modern",
        question: "The photoelectric effect demonstrates that light behaves as:",
        type: QuestionType.MCQ,
        options: ["Particles (photons)", "Waves only", "Both always", "Neither"],
        correctAnswer: "Particles (photons)",
        difficulty: 0.4,
        hints: ["Einstein's explanation of photoelectric effect"],
        explanation: "Photoelectric effect proves particle nature of light (photons)",
      },
    ],
  },
  Chemistry: {
    default: [
      {
        id: "chem-q1",
        topicId: "chem-atomic",
        question: "How many electrons can the second shell (n=2) hold?",
        type: QuestionType.MCQ,
        options: ["8", "2", "18", "32"],
        correctAnswer: "8",
        difficulty: 0.3,
        hints: ["Max electrons = 2n²"],
        explanation: "2n² = 2(2)² = 8 electrons",
      },
      {
        id: "chem-q2",
        topicId: "chem-bonding",
        question: "What type of bond forms between Na and Cl in NaCl?",
        type: QuestionType.MCQ,
        options: ["Ionic", "Covalent", "Metallic", "Hydrogen"],
        correctAnswer: "Ionic",
        difficulty: 0.2,
        hints: ["Metal + Non-metal = ?"],
        explanation: "Na (metal) transfers electron to Cl (non-metal), forming ionic bond",
      },
      {
        id: "chem-q3",
        topicId: "chem-organic",
        question: "What is the functional group in alcohols?",
        type: QuestionType.MCQ,
        options: ["-OH", "-COOH", "-CHO", "-CO-"],
        correctAnswer: "-OH",
        difficulty: 0.3,
        hints: ["Think of ethanol: C₂H₅OH"],
        explanation: "Alcohols contain the hydroxyl (-OH) functional group",
      },
      {
        id: "chem-q4",
        topicId: "chem-thermo",
        question: "An exothermic reaction has ΔH that is:",
        type: QuestionType.MCQ,
        options: ["Negative", "Positive", "Zero", "Undefined"],
        correctAnswer: "Negative",
        difficulty: 0.3,
        hints: ["Exo = releases heat"],
        explanation: "Exothermic reactions release energy, so ΔH < 0",
      },
      {
        id: "chem-q5",
        topicId: "chem-equilibrium",
        question: "According to Le Chatelier's principle, adding more reactant will:",
        type: QuestionType.MCQ,
        options: ["Shift equilibrium to products", "Shift to reactants", "No effect", "Stop the reaction"],
        correctAnswer: "Shift equilibrium to products",
        difficulty: 0.4,
        hints: ["System opposes the change"],
        explanation: "Adding reactant shifts equilibrium forward (towards products) to reduce the disturbance",
      },
    ],
  },
  Biology: {
    default: [
      {
        id: "bio-q1",
        topicId: "bio-cell",
        question: "Which organelle is called the 'powerhouse of the cell'?",
        type: QuestionType.MCQ,
        options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi body"],
        correctAnswer: "Mitochondria",
        difficulty: 0.2,
        hints: ["It produces ATP"],
        explanation: "Mitochondria generate ATP through cellular respiration",
      },
      {
        id: "bio-q2",
        topicId: "bio-genetics",
        question: "DNA is made up of nucleotides containing which bases?",
        type: QuestionType.MCQ,
        options: ["A, T, G, C", "A, U, G, C", "A, T, G, U", "A, B, C, D"],
        correctAnswer: "A, T, G, C",
        difficulty: 0.3,
        hints: ["RNA has U instead of T"],
        explanation: "DNA: Adenine, Thymine, Guanine, Cytosine (RNA uses Uracil instead of Thymine)",
      },
      {
        id: "bio-q3",
        topicId: "bio-evolution",
        question: "Who proposed the theory of natural selection?",
        type: QuestionType.MCQ,
        options: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "James Watson"],
        correctAnswer: "Charles Darwin",
        difficulty: 0.2,
        hints: ["Origin of Species (1859)"],
        explanation: "Charles Darwin proposed natural selection in 'On the Origin of Species'",
      },
      {
        id: "bio-q4",
        topicId: "bio-physiology",
        question: "Which organ filters blood and produces urine?",
        type: QuestionType.MCQ,
        options: ["Kidney", "Liver", "Heart", "Lungs"],
        correctAnswer: "Kidney",
        difficulty: 0.2,
        hints: ["Part of the excretory system"],
        explanation: "Kidneys filter blood, remove waste, and produce urine",
      },
      {
        id: "bio-q5",
        topicId: "bio-ecology",
        question: "What is the term for organisms that make their own food?",
        type: QuestionType.MCQ,
        options: ["Autotrophs", "Heterotrophs", "Decomposers", "Parasites"],
        correctAnswer: "Autotrophs",
        difficulty: 0.2,
        hints: ["Plants are examples"],
        explanation: "Autotrophs (like plants) produce food via photosynthesis",
      },
    ],
  },
  "Computer Science": {
    default: [
      {
        id: "cs-q1",
        topicId: "cs-programming",
        question: "What will `print(2 + 3 * 4)` output in Python?",
        type: QuestionType.MCQ,
        options: ["14", "20", "9", "Error"],
        correctAnswer: "14",
        difficulty: 0.2,
        hints: ["Order of operations: multiplication before addition"],
        explanation: "3 * 4 = 12, then 2 + 12 = 14",
      },
      {
        id: "cs-q2",
        topicId: "cs-dsa",
        question: "What is the time complexity of binary search?",
        type: QuestionType.MCQ,
        options: ["O(log n)", "O(n)", "O(n²)", "O(1)"],
        correctAnswer: "O(log n)",
        difficulty: 0.4,
        hints: ["Divides search space in half each time"],
        explanation: "Binary search halves the array each step: O(log n)",
      },
      {
        id: "cs-q3",
        topicId: "cs-oop",
        question: "Which OOP principle allows a class to inherit from another?",
        type: QuestionType.MCQ,
        options: ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction"],
        correctAnswer: "Inheritance",
        difficulty: 0.3,
        hints: ["Child class extends parent class"],
        explanation: "Inheritance allows a class to inherit properties and methods from another",
      },
      {
        id: "cs-q4",
        topicId: "cs-databases",
        question: "Which SQL command retrieves data from a database?",
        type: QuestionType.MCQ,
        options: ["SELECT", "INSERT", "UPDATE", "DELETE"],
        correctAnswer: "SELECT",
        difficulty: 0.2,
        hints: ["To query/read data"],
        explanation: "SELECT is used to retrieve/query data from tables",
      },
      {
        id: "cs-q5",
        topicId: "cs-systems",
        question: "What does CPU stand for?",
        type: QuestionType.MCQ,
        options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"],
        correctAnswer: "Central Processing Unit",
        difficulty: 0.1,
        hints: ["The 'brain' of the computer"],
        explanation: "CPU = Central Processing Unit - executes instructions",
      },
    ],
  },
};

export function getDiagnosticQuestions(subject: string, examGoal: string): Question[] {
  const subjectQuestions = DIAGNOSTIC_QUESTIONS[subject];
  if (!subjectQuestions) {
    return DIAGNOSTIC_QUESTIONS["Mathematics"]?.default || [];
  }

  const examLower = examGoal.toLowerCase();

  if (examLower.includes("jee") || examLower.includes("iit")) {
    return subjectQuestions["IIT JEE"] || subjectQuestions.default || [];
  }
  if (examLower.includes("ap ") || examLower.includes("ap calc") || examLower.includes("advanced placement")) {
    return subjectQuestions["AP Calculus"] || subjectQuestions.default || [];
  }
  if (examLower.includes("gcse")) {
    return subjectQuestions["GCSE"] || subjectQuestions.default || [];
  }

  return subjectQuestions.default || [];
}
